config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    #root 'users#new'
    resources :users do
      resources :posts
      resources :addresses
    end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id            :integer          not null, primary key
#  name          :string
#  gender        :string
#  email         :string
#  password      :string
#  date_of_birth :datetime
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class User < ApplicationRecord
  has_many :addresses, dependent: :destroy
  has_many :posts , dependent: :destroy
  validates :name, format: {with: /\A[a-zA-Z]+ [a-zA-Z]+ [a-zA-Z]+/, message: 'firstName middle_name last_name (In this format)'}
  validates :gender, presence: true
  validates :email, presence: true
  validates :password, length:{minimum: 5}, confirmation: true
  validates :date_of_birth, presence: true

  def vaildate_date
    start_date = "1-1-2000"
    end_date = DateTime.now
    date = date_of_birth
    date.between?(Date.parse(start_date), end_date)
  end
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  def show
  end

  def new
    @user = User.find(params[:user_id])
  end

  def edit
  end

  def index
  end

  def create
    @user = User.find(params[:user_id])
    @address = @user.addresses.create(address_params)

    redirect_to user_address_path
  end

  private
  def address_params
    params.require(:address).permit(:city, :state, :country)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def create
    @user = User.find(params[:user_id])
    @post = @user.posts.create(post_params)
    redirect_to user_path(@user)
  end

  def destroy
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])
    @post.destroy

    redirect_to user_path(@user)
  end

  private
  def post_params
    params.require(:post).permit(:content)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @user = User.all
    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @user }
    end
  end

  def new
    @user = User.new
  end
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to users_path
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html
      format.json{ render :json  => @user}
    end
    #render 'users#index'
  end
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :password, :email, :date_of_birth, :gender)
  end

end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/new.html.erb
<h1>Hello</h1>
<form>
  <%= form_with scope: :address, url: user_addresses_path(@user), local: true do |form|%>
  <%= form.label :City %>
  <%= form.text_field :city %><br><br>

  <%= form.label :State %>
  <%= form.text_field :state %><br><br>

  <%= form.label :Country %>
  <%= form.text_field :country %>

  <%= form.submit %>
  <% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Facebook
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/users/edit.html.erb
<h1>Edit user</h1>

<%= form_with(model: @user) do |form| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.label :Name%><br>
  <%= form.text_field :name%><br><br>

  <%= form.label :Password%><br>
  <%= form.password_field :password%><br><br>

  <%= form.label :'Confirm Password'%><br>
  <%= form.password_field :password_confirmation%><br><br>

  <%= form.label :Gender%><br>
  <%= form.radio_button :gender, true, :class => 'form-control radio-inline' %> Male
  <%= form.radio_button :gender, false, :class => 'form-control radio-inline' %>Female<br><br>

  <%= form.label :Email%><br>
  <%= form.text_field :email%><br><br>

  <%= form.label :'Date Of Birth'%><br>
  <%= form.date_field :date_of_birth%><br><br>

  <%= form.button :submit%>
  <%= form.button :reset%>

<% end %>
<%= link_to 'back', users_path%>

app/views/users/index.html.erb
<h1>All Users</h1>
<table border="1">
  <%@user.each do |user|%>
  <tr>
    <td><%=user.name%></td>
    <td><%=user.password%></td>
    <td><%=user.gender%></td>
    <td><%=user.email%></td>
    <td><%=user.date_of_birth%></td>
    <td><%=link_to 'Profile', user_path(user)%>
    <td><%=link_to 'Edit', edit_user_path(user)%>
    <td><%=link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?'}%></td>
  </tr>
  <%end%>
</table>

app/views/users/new.html.erb
<%= form_with scope: :user, url: users_path, local: true do |form|%>
  <p>
    <% if @user.errors.any? %>
      <div id = "Error">
        <h2>
          <%= pluralize(@user.errors.count, "error")%>
          prohibited
          Saving details....
        </h2>
        <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
  <% end %>
    <%= form.label :Name%><br>
    <%= form.text_field :name%><br><br>

    <%= form.label :Password%><br>
    <%= form.password_field :password%><br><br>

    <%= form.label :'Confirm Password'%><br>
    <%= form.password_field :password_confirmation%><br><br>

    <%= form.label :Gender%><br>
    <%= form.radio_button :gender, true, :class => 'form-control radio-inline' %> Male
    <%= form.radio_button :gender, false, :class => 'form-control radio-inline' %>Female<br><br>

    <%= form.label :Email%><br>
    <%= form.text_field :email%><br><br>

    <%= form.label :'Date Of Birth'%><br>
    <%= form.date_field :date_of_birth%><br><br>

    <%= form.button :submit%>
    <%= form.button :reset%>
  </p>
  <%end%>

app/views/users/show.html.erb
<table border="1">
  <tr><td><%= @user.name %></td>
  <% if @user.gender? %>
    <td> Male </tb>
  <% else %>
    <td>Female</td>
  <%end%>
  <td><%= @user.email %></td>
  <td><%= @user.date_of_birth %></td></tr>
</table >
<!-- <%= link_to 'add details', new_user_address_path(@user)%> -->

<h1> Posts </h1>
<% @user.posts.each do |post| %>
<%= Time.now %>
<%= post.content%>
<p>
    <%= link_to 'Destroy Post',
        [post.user, post],
        method: :delete, data: {confirm: 'Are you sure?'} %>
</p>
<% end %>
<h2>Add Post</h2>
<%= form_with(model: [ @user, @user.posts.build ], local: true) do |form|%>
  <p>
    <%= form.label :Post%><br>
    <%= form.text_area :content%>
  </p>
  <%= form.submit%>
  <% end %>
<%= link_to 'back', users_path%>